apiVersion: v1
kind: Service
metadata:
  name: identityservernpservice-srv
spec:
  type: NodePort
  selector:
    app: identityserver
  ports:
  - name: identityserver
    protocol: TCP
    port: 80
    targetPort: 80
